#!/bin/sh
pairs="\
application/vnd.oasis.opendocument.image:feh.desktop
x-scheme-handler/discord:vesktop.desktop
application/:zaread.desktop
string:zaread.desktop
image/:feh.desktop
video/:mpv.desktop
text/:nvim.desktop"
echo "$pairs" | while IFS=":" read -r types app ; do
    grep ^"$types" /usr/share/mime/types |
        while read -r type; do
            echo "$app" "->" "$type"
            xdg-mime default "$app" "$type"
    done
done
