#!/bin/sh
MONITOR_STATE="$("$(dirname "$0")/../detect-monitor")"
if [ "$MONITOR_STATE" = "PRIMARY" ] || [ "$MONITOR_STATE" = "NONE" ]; then
    BRIGHTNESS_VALUE=0
else
    BRIGHTNESS_VALUE=$(ddcutil getvcp 10 2>/dev/null | awk -F'=' '/current value/ {print $2}' | awk -F',' '{print $1}' | xargs) || "0"
fi
display-brightness "$BRIGHTNESS_VALUE"
