#!/bin/sh
MONITOR_STATE="$("$(dirname "$0")/../detect-monitor")"
if [ "$MONITOR_STATE" = "SECONDARY" ] || [ "$MONITOR_STATE" = "NONE" ]; then
    BRIGHTNESS_VALUE=0
else
    BRIGHTNESS_VALUE=$(brightnessctl | grep -o "(.*" | tr -d "()")
fi
display-brightness "${BRIGHTNESS_VALUE%\%}"
